<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
					<a href="index.php?route=contact">Contact</a>
					</li>
				</ul>
			</nav>
		</header>
			<?php
				// Chargement des templates en fonction de $route
				if ($route === "home") {
					require "templates/home.phtml";
				} elseif ($route === "about") {
					require "templates/about.phtml";
				} elseif ($route === "notFound") {
					require "templates/notFound.phtml";
				}
			?>
		?>
	</body>
</html>
